Repository tikv/rust-rocksdb, pull requests merged in 2020-08, with the labels that each got.

#526 add refill_period for creating rate limiter
  src/rocksdb_options.rs
  tests/cases/test_rocksdb_options.rs
Labels: status/LGT1, status/can-merge

#525 add support to set compression options
  librocksdb_sys/src/lib.rs
  src/rocksdb_options.rs
Labels: status/LGT1

#531 *-sys: use release lz4
  librocksdb_sys/Cargo.toml
  librocksdb_sys/libtitan_sys/Cargo.toml
Labels: status/LGT1

#532 add support to set compression options (#525)
  librocksdb_sys/src/lib.rs
  src/rocksdb_options.rs
Labels: status/LGT1, type/cherry-pick

#533 add more perf context counters
  librocksdb_sys/crocksdb/c.cc
  librocksdb_sys/crocksdb/crocksdb/c.h
  librocksdb_sys/src/lib.rs
  src/perf_context.rs
Labels: status/LGT2

#512 Add SST partitioner interface
  Cargo.toml
  Makefile
  librocksdb_sys/crocksdb/c.cc
  librocksdb_sys/crocksdb/crocksdb/c.h
  librocksdb_sys/src/lib.rs
  rust-toolchain
  src/lib.rs
  src/rocksdb_options.rs
  src/sst_partitioner.rs
Labels: sig/engine, status/LGT2
