Repository tikv/rust-rocksdb, pull requests merged in 2020-12, with the labels that each got.

#573 Add create_missing_column_families option.
  librocksdb_sys/src/lib.rs
  src/rocksdb_options.rs
Labels: first-time-contributor, status/LGT2, status/can-merge

#590 Fix missing export of SubcompactionJobInfo
  src/lib.rs
Labels: status/LGT1

#592 Import some variable public
  src/lib.rs
Labels: first-time-contributor, status/LGT2
