Repository tikv/rust-rocksdb, pull requests merged in 2021-02, with the labels that each got.

#608 fix arm64 ci
  .travis.yml
Labels: first-time-contributor, status/LGT2

#607 update rust toolchain
  librocksdb_sys/build.rs
  rust-toolchain
  src/merge_operator.rs
  src/rocksdb.rs
Labels: status/LGT2

#603 add `get_level` for `ColumnFamilyMetaData`
  src/metadata.rs
Labels: first-time-contributor, status/LGT2, status/can-merge

#605 Fix build failures on apple silicon
  librocksdb_sys/Cargo.toml
  librocksdb_sys/librocksdb_cloud_sys/cmake_modules/rocksdb_flags.cmake
  src/encryption.rs
Labels: first-time-contributor, status/LGT2

#610 update to zstd1.4.8
  librocksdb_sys/Cargo.toml
Labels: first-time-contributor, status/LGT2
