Repository tikv/rust-rocksdb, pull requests merged in 2021-01, with the labels that each got.

#593 use `uname -m` instead of `uname -p` to get the architecture
  scripts/generate-bindings.sh
Labels: first-time-contributor, status/LGT1

#595 refactor usage of `Arc`
  src/encryption.rs
  src/file_system.rs
  src/lib.rs
  src/rocksdb.rs
Labels: status/LGT2

#598 change sst_partitioner calls to be mutable
  src/sst_partitioner.rs
Labels: status/LGT2

#599 change sst_partitioner calls to be mutable (#598)
  src/sst_partitioner.rs
Labels: status/LGT2, type/cherry-pick
